Repository Trinityyi/boardeaux, pull requests merged in 2020-08, with the labels that each got.

#43 Add Modal component
  .eslintignore
  .eslintrc.json
  package.json
  public/index.html
  src/components/App.jsx
  src/components/Card.jsx
  src/components/CardModalDialog.jsx
  src/components/Column.jsx
  src/components/EditableText.jsx
  src/components/Header.jsx
  src/components/MainArea.jsx
  src/components/Modal.jsx
  src/store/index.js
  src/styles/_modal.scss
  src/styles/index.scss
  src/test/components/Header.test.jsx
  src/test/utils/renderConnected.js
Labels: enhancement

#45 Json Storage
  public/index.html
  src/components/App.jsx
  src/components/Card.jsx
  src/components/CardModalDialog.jsx
  src/components/Column.jsx
  src/components/Header.jsx
  src/components/MainArea.jsx
  src/components/MenuModalDialog.jsx
  src/storage/index.js
  src/store/actionTypes.js
  src/store/actions.js
  src/store/board.js
  src/store/cards.js
  src/store/columns.js
  src/store/index.js
  src/store/interface.js
  src/store/reducer.js
  src/styles/_main_menu.scss
  src/styles/_modal.scss
  src/styles/index.scss
  src/test/components/Column.test.jsx
  src/test/utils/renderConnected.js
Labels: enhancement

#46 Add Markdown support
  package-lock.json
  package.json
  src/components/CardModalDialog.jsx
  src/components/EditableText.jsx
  src/utils/index.js
Labels: enhancement

#47 Maintenance and styles for modals
  public/index.html
  public/splash.png
  src/components/App.jsx
  src/components/Card.jsx
  src/components/CardModalDialog.jsx
  src/components/EditableText.jsx
  src/components/MainArea.jsx
  src/components/MenuModalDialog.jsx
  src/components/MenuPanel.jsx
  src/components/Modal.jsx
  src/hooks/useClickSelector.js
  src/styles/_card.scss
  src/styles/_column.scss
  src/styles/_input.scss
  src/styles/_label.scss
  src/styles/_main_menu.scss
  src/styles/_markdown.scss
  src/styles/_menu.scss
  src/styles/_modal.scss
  src/styles/index.scss
  src/test/components/AddButton.test.jsx
  src/test/components/Card.test.jsx
  src/test/components/CardModalDialog.test.jsx
  src/test/components/MenuPanel.test.jsx
  src/test/components/Modal.test.jsx
Labels: enhancement, maintenance

#48 Add Card Priority to reducer
  src/components/Card.jsx
  src/components/CardModalDialog.jsx
  src/shared/index.js
  src/store/cards.js
  src/styles/_card.scss
  src/test/components/Card.test.jsx
  src/test/fixtures/cards.js
Labels: enhancement

#49 Add drag and drop functionality
  package-lock.json
  package.json
  src/components/App.jsx
  src/components/Card.jsx
  src/components/Column.jsx
  src/store/columns.js
  src/store/interface.js
  src/styles/_card.scss
  src/styles/_column.scss
  src/test/components/Card.test.jsx
  src/test/components/CardModalDialog.test.jsx
  src/test/components/Column.test.jsx
  src/test/components/Header.test.jsx
  src/test/components/MenuPanel.test.jsx
  src/test/test_utils/renderConnected.js
  src/test/test_utils/renderDndConnected.js
  src/test/utils/index.test.js
  src/utils/index.js
Labels: enhancement

#50 Tags
  package-lock.json
  package.json
  src/components/AddButton.jsx
  src/components/Card.jsx
  src/components/CardModalDialog.jsx
  src/components/Column.jsx
  src/components/EditableText.jsx
  src/components/MainArea.jsx
  src/components/MenuPanel.jsx
  src/components/Popover.jsx
  src/components/Tag.jsx
  src/components/TagInput.jsx
  src/components/TagPanel.jsx
  src/storage/index.js
  src/store/actionTypes.js
  src/store/actions.js
  src/store/cards.js
  src/store/reducer.js
  src/store/tags.js
  src/styles/_card.scss
  src/styles/_column.scss
  src/styles/_input.scss
  src/styles/_label.scss
  src/styles/_menu.scss
  src/styles/_popover.scss
  src/styles/_tag.scss
  src/styles/index.scss
  src/test/components/Card.test.jsx
  src/test/components/CardModalDialog.test.jsx
  src/test/components/Column.test.jsx
  src/test/fixtures/cards.js
  src/test/utils/index.test.js
  src/utils/index.js
Labels: enhancement

#52 Update import logic
  src/storage/index.js
  src/store/board.js
  src/store/cards.js
  src/store/columns.js
  src/store/tags.js
Labels: Priority: low, enhancement, maintenance
